import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Link from '@/node_modules/next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Home Page',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex justify-between m-3 ">
          <h1>LINGUIN</h1>
          <nav className="">
            <Link className="m-3" href="/">
              HOME
            </Link>
            <Link className="m-3" href="./articals">
              ARTICALS
            </Link>
            <Link className="m-3" href="./posts">
              POSTS
            </Link>
          </nav>
        </div>
        {children}
      </body>
    </html>
  );
}
